query GetOrders {
  orders {
    id
    orderDate
    description
    totalAmount
    depositAmount
    isDelivery
    status
    otherNotes
    customer {
      id
      firstName
      lastName
      contactNumber
      email
    }
  }
}